# Generated by Django 2.0.2 on 2018-05-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_booking_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='daily_rent',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
